apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: cadvisor
  namespace: {{.Release.Namespace}}
  annotations:
    seccomp.security.alpha.kubernetes.io/defaultProfileName: "runtime/default"
spec:
  allowPrivilegeEscalation: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
  allowedHostPaths:
  - pathPrefix: "/"
  - pathPrefix: "/var/run"
  - pathPrefix: "/sys"
  - pathPrefix: "/var/lib/docker"
  - pathPrefix: "/dev/disk"

  requiredDropCapabilities:
    - NET_RAW
