{{if .Values.node_port}}
apiVersion: v1
kind: Service
metadata:
  name: cadvisor-np-service
  namespace: {{.Release.Namespace}}
  labels:
    app: cadvisor
spec:
  type: NodePort
  selector:
    name: cadvisor
  ports:
    - name: cadvisor
      protocol: TCP
      port: {{.Values.port}}
      nodePort: {{.Values.node_port}}
{{end}}
