# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

    ldflags:
      - -X github.com/google/cadvisor/version.Version={{.Tag}}
      - -X github.com/google/cadvisor/version.Revision={{.Commit}}
      - -X github.com/google/cadvisor/version.Branch={{.Branch}}
      - -X github.com/google/cadvisor/version.BuildUser="unknown"
      - -X github.com/google/cadvisor/version.BuildDate={{.Date}}
      - -X github.com/google/cadvisor/version.GoVersion={{.Major}}.{{.Minor}}.{{.Patch}}
checksum:
  name_template: 'checksums.txt'
