builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -tags=netgo
    ldflags:
      - -X github.com/google/cadvisor/version.Version={{.Tag}}
      - -X github.com/google/cadvisor/version.Revision={{.Commit}}
      - -X github.com/google/cadvisor/version.Branch={{.Branch}}
      - -X github.com/google/cadvisor/version.BuildUser={{.Env.GITHUB_ACTOR}}
      - -X github.com/google/cadvisor/version.BuildDate={{.Date}}
      - -X github.com/google/cadvisor/version.GoVersion=1.16
checksum:
  name_template: checksums.txt
