# This patch is an example of setting arguments for the cAdvisor container.
# This set of arguments mirrors what the kubelet currently uses for cAdvisor,
# enables only cpu, memory, diskIO, disk and network metrics, and shows only
# container metrics.
enable_metrics:
  - app
  - cpu
  - disk
  - diskIO
  - memory
  - network
  - process

port: 8080

# Configure the container security context.
securityContext:
  privileged: true  # Note: Some metrics are unavailable without privileges.
  allowPrivilegeEscalation: true
  runAsNonRoot: false
  readOnlyRootFilesystem: true
  runAsGroup: 2000
  capabilities:
    drop:
      - ALL

docker_only: true

image: gcr.io/cadvisor/cadvisor:v0.41.0@sha256:c4a53e233abff2a995d6978462c92801d045c70298d21be3b2768d465f865a44
imagePullPolicy: Always
