name: Image

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./deploy/Dockerfile
          platforms: linux/amd64,linux/arm,linux/arm64,linux/ppc64le
          tags: cadvisor:latest
