name: Release
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-20.04
    # The only reason to use strategy.matrix is to pass GOLANG_VERSION env variable while keeping Go version number
    # in single place.
    strategy:
      matrix:
        golang: [1.16]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.golang }}
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: v0.160.0
        args: release --rm-dist --debug --config ../.goreleaser.yml --skip-sign --debug
        workdir: ./cmd
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GOLANG_VERSION: ${{ matrix.golang }}