name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    defaults:
      run:
        working-directory: "./cmd"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: ["release", "--rm-dist", "--debug", "--config", "../.goreleaser.yml", "--skip-sign", "--debug"]
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}